import React,{useEffect,useMemo,useState}from'react';import{createRoot}from'react-dom/client';import{pipeline,env}from'@huggingface/transformers';import{Search,Plus,ArrowUpRight,Sparkles,Users,X,ChevronRight,Clock3,MapPin,Link2,Check,Command,SlidersHorizontal,Brain,LoaderCircle,RefreshCw}from'lucide-react';import'./styles.css';
env.allowLocalModels=false;env.useBrowserCache=true;
const people=[['p1','Maya Chen','Product Designer','London','MC'],['p2','Jonas Berg','Principal Developer','Oslo','JB'],['p3','Ines Martin','Strategist','Barcelona','IM'],['p4','Lukas Weber','Creative Technologist','Bonn','LW'],['p5','Sofia Rossi','Product Designer','Amsterdam','SR']];
const projects=[['pr1','AI Research Companion','Prototype','London','Product × AI'],['pr2','Everyday Experiments','Self-initiated','Amsterdam','Research × Technology'],['pr3','Machine Windows','Self-initiated','Bonn','AI × Visual Design'],['pr4','A New Way to Learn','Prototype','Oslo','Product × Research']];
let memories=[
{id:'m1',title:'Making AI uncertainty visible',type:'Learning',office:'London',year:'2026',tags:['AI','Trust','Interaction'],summary:'Users understood AI-generated answers better when uncertainty was expressed as part of the interaction rather than hidden in a disclaimer.',context:'We were exploring how an AI product could communicate confidence without making every response feel technical.',tried:'Confidence labels, expandable reasoning, visual cues and progressive disclosure.',finding:'A small amount of contextual uncertainty worked better than a persistent confidence score. People wanted to know what the system was unsure about, not just how unsure it was.',decision:'Move uncertainty into moments where it changes a user decision. Avoid turning confidence into a dashboard metric.',looking:'Test how this behaves on mobile, where space is limited.',people:['p1','p4'],projectId:'pr1',related:['m2','m4']},
{id:'m2',title:'When less automation worked better',type:'Decision',office:'Oslo',year:'2025',tags:['AI','Automation','Research'],summary:'Removing one automated step gave people more confidence because they understood what was happening.',context:'The team wanted to automate a repetitive part of a learning workflow.',tried:'Fully automated flow, assisted flow and explicit user confirmation.',finding:'The assisted version performed better in qualitative testing because users retained a sense of control.',decision:'Automate the work, not the decision.',looking:'Explore whether the same principle holds for expert users.',people:['p2','p5'],projectId:'pr4',related:['m1','m3']},
{id:'m3',title:'The prototype taught us more than the spec',type:'Experiment',office:'Bonn',year:'2026',tags:['Prototype','AI','Code'],summary:'A rough interactive prototype exposed assumptions about the concept that several rounds of discussion had missed.',context:'We were exploring a generative visual system before committing to a polished direction.',tried:'Static concepts, motion tests and a small coded prototype.',finding:'Interaction revealed timing and attention problems that were invisible in static screens.',decision:'Prototype behaviour early when the concept depends on motion or emergence.',looking:'Build smaller experiments and test them sooner.',people:['p4','p1'],projectId:'pr3',related:['m1','m5']},
{id:'m4',title:'Progressive disclosure reduces cognitive load',type:'Learning',office:'Amsterdam',year:'2025',tags:['UX','Onboarding','Systems'],summary:'People engaged more confidently when a complex capability was introduced in layers instead of all at once.',context:'We explored ways to introduce a multi-step capability without turning the first experience into a tutorial.',tried:'Full feature overview, guided tour and progressive disclosure.',finding:'Progressive disclosure helped people build a mental model while doing the task.',decision:'Introduce complexity at the moment it becomes useful.',looking:'Test with returning users who already know the product.',people:['p5','p3'],projectId:'pr2',related:['m1','m2']},
{id:'m5',title:'A rejected direction can be reusable knowledge',type:'Reflection',office:'Barcelona',year:'2026',tags:['Strategy','Process','Research'],summary:'Documenting why a direction was rejected was more useful to later teams than documenting the final direction alone.',context:'Several promising routes were explored and abandoned during early framing.',tried:'Final-output documentation versus decision-led notes.',finding:'The “why not” context prevented later teams from reopening already-tested paths without understanding the trade-offs.',decision:'Capture decisions with the reasoning behind them, not just the outcome.',looking:'Find the smallest useful format for documenting a decision.',people:['p3','p2'],projectId:'pr2',related:['m3','m4']},
{id:'m6',title:'Designing trust into intelligent systems',type:'Learning',office:'London',year:'2025',tags:['AI','Trust','UX'],summary:'People trusted an intelligent system more when it showed the boundaries of what it could do instead of pretending to be certain.',context:'We explored how to make an AI assistant feel capable without making it feel overconfident.',tried:'Anthropomorphic copy, confidence indicators and explicit capability boundaries.',finding:'Clear boundaries were more reassuring than personality-heavy explanations.',decision:'Make capability boundaries visible at the point of uncertainty.',looking:'Explore how this changes for expert users.',people:['p1','p4'],projectId:'pr1',related:['m1','m2']}
];
const personById=id=>people.find(p=>p[0]===id);const projectById=id=>projects.find(p=>p[0]===id);
function memoryText(m){return[m.title,m.summary,m.context,m.tried,m.finding,m.decision,m.looking,m.type,m.office,m.tags.join(' ')].join('. ')}
let extractorPromise=null;async function getExtractor(){if(!extractorPromise){extractorPromise=pipeline('feature-extraction','Xenova/all-MiniLM-L6-v2',{dtype:'fp32'});}return extractorPromise}
async function embed(text){const model=await getExtractor();const out=await model(text,{pooling:'mean',normalize:true});return Array.from(out.data)}
function dot(a,b){let s=0;for(let i=0;i<a.length;i++)s+=a[i]*b[i];return s}
function lexicalScore(q,m){const words=q.toLowerCase().split(/\W+/).filter(Boolean);const text=memoryText(m).toLowerCase();return words.reduce((s,w)=>s+(text.includes(w)?1:0),0)/Math.max(words.length,1)}
function App(){const[v,setV]=useState('home'),[q,setQ]=useState(''),[sel,setSel]=useState(),[add,setAdd]=useState(false),[toast,setToast]=useState(''),[typ,setTyp]=useState('All'),[off,setOff]=useState('All'),[semantic,setSemantic]=useState(true),[status,setStatus]=useState('idle'),[scores,setScores]=useState({}),[form,setForm]=useState({title:'',context:'',finding:'',type:'Learning',office:'London'});
const flash=x=>{setToast(x);setTimeout(()=>setToast(''),2200)};
const runSemantic=async query=>{if(!query.trim()){setScores({});setStatus('idle');return}setStatus('loading');try{const qe=await embed(query);const pairs=await Promise.all(memories.map(async m=>[m.id,await embed(memoryText(m))]));const next={};pairs.forEach(([id,e])=>next[id]=dot(qe,e));setScores(next);setStatus('ready')}catch(e){console.error(e);setStatus('fallback');flash('AI search unavailable — using local keyword search')}};
useEffect(()=>{const t=setTimeout(()=>{if(semantic)runSemantic(q)},350);return()=>clearTimeout(t)},[q,semantic]);
const results=useMemo(()=>{let r=memories.filter(m=>(typ==='All'||m.type===typ)&&(off==='All'||m.office===off));if(!q)return r;if(semantic&&status==='ready')return r.map(m=>({...m,_score:(scores[m.id]||0)+lexicalScore(q,m)*.08})).sort((a,b)=>b._score-a._score);return r.map(m=>({...m,_score:lexicalScore(q,m)})).filter(m=>m._score>0).sort((a,b)=>b._score-a._score)},[q,typ,off,semantic,status,scores]);
const save=()=>{if(!form.title||!form.finding)return flash('Add a title and a learning first');memories.unshift({id:'m'+Date.now(),title:form.title,type:form.type,office:form.office,year:'2026',tags:['New'],summary:form.finding,context:form.context,tried:'Captured directly in BB Memory.',finding:form.finding,decision:'To be explored.',looking:'',people:[],projectId:'',related:[]});setAdd(false);setForm({title:'',context:'',finding:'',type:'Learning',office:'London'});setScores({});setStatus('idle');flash('Memory saved — ready to be discovered by AI search')};
return <div className="app"><aside><div className="brand"><b>bb</b><div><strong>memory</strong><small>collective knowledge</small></div></div><nav>{[['home','Home'],['memories','Memories'],['people','People'],['projects','Projects']].map(x=><button className={v===x[0]?'active':''} onClick={()=>setV(x[0])} key={x[0]}>{x[1]}{x[0]==='memories'&&<span>{memories.length}</span>}</button>)}</nav><div className="bottom"><small>● One team · 5 offices</small><button className="add" onClick={()=>setAdd(true)}><Plus size={15}/> Add memory</button></div></aside><main><header><span>BB / MEMORY</span><div><em><Command size={12}/> K</em><i>BW</i></div></header>{v==='home'&&<Home q={q} setQ={setQ} go={()=>setV('memories')} open={setSel} status={status}/>} {v==='memories'&&<Library q={q} setQ={setQ} results={results} typ={typ} setTyp={setTyp} off={off} setOff={setOff} open={setSel} add={()=>setAdd(true)} semantic={semantic} setSemantic={setSemantic} status={status} retry={()=>runSemantic(q)}/>} {v==='people'&&<People/>}{v==='projects'&&<Projects/>}</main>{sel&&<Modal m={sel} close={()=>setSel(null)} open={setSel} flash={flash}/>} {add&&<Add form={form} setForm={setForm} close={()=>setAdd(false)} save={save}/>} {toast&&<div className="toast"><Check size={14}/>{toast}</div>}</div>}
function Home({q,setQ,go,open,status}){return <section className="home"><div className="hero"><label>● BB'S COLLECTIVE MEMORY</label><h1>What are you<br/><i>trying to figure out?</i></h1><p>Find what BB has already learned — across projects, people, experiments and offices.</p><div className="search"><Search/><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&go()} placeholder="Try: I'm designing an AI onboarding experience…"/><button onClick={go}><ArrowUpRight/></button></div><div className="ai-state">{status==='loading'?<><LoaderCircle className="spin"/> Understanding your question…</>:status==='ready'?<><Brain/> Semantic search is ready</>:<><Sparkles/> AI understands meaning, not just keywords</>}</div><div className="try"><small>TRY ASKING</small><button onClick={()=>{setQ('AI onboarding');go()}}>AI onboarding</button><button onClick={()=>{setQ('user trust');go()}}>user trust</button><button onClick={()=>{setQ('what didn’t work');go()}}>what didn’t work</button></div></div><div className="homegrid"><div><small className="kicker">RECENTLY REMEMBERED</small><h2>Things worth knowing</h2>{memories.slice(0,3).map(m=><Card m={m} open={open} key={m.id}/>)}</div><div className="idea"><div className="art"><span/><span/><span/></div><small className="kicker">THE IDEA</small><h2>Knowledge shouldn't disappear when a project ends.</h2><p>BB Memory connects the context behind the work — so the next person can pick up where someone else left off.</p></div></div></section>}
function Library({q,setQ,results,typ,setTyp,off,setOff,open,add,semantic,setSemantic,status,retry}){return <section className="page"><div className="title"><div><small>LIBRARY</small><h1>Memories</h1><p>Useful things BB has learned along the way.</p></div><button className="primary" onClick={add}><Plus size={15}/> Add memory</button></div><div className="toolbar"><div className="mini"><Search/><input value={q} onChange={e=>setQ(e.target.value)} placeholder="Search by problem, idea, project…"/></div><div className="filters"><button className={'ai-toggle '+(semantic?'on':'')} onClick={()=>setSemantic(!semantic)}><Brain size={13}/>{semantic?'AI search':'Keyword search'}</button><SlidersHorizontal/><select value={typ} onChange={e=>setTyp(e.target.value)}><option>All</option><option>Learning</option><option>Decision</option><option>Experiment</option><option>Reflection</option></select><select value={off} onChange={e=>setOff(e.target.value)}><option>All</option>{['Amsterdam','Barcelona','Bonn','London','Oslo'].map(x=><option key={x}>{x}</option>)}</select></div></div>{q&&<div className="search-status">{status==='loading'?<><LoaderCircle className="spin"/> Searching the collective memory…</>:status==='fallback'?<><RefreshCw size={13}/> Keyword fallback <button onClick={retry}>Retry AI</button></>:<><Brain size={13}/> <b>{results.length}</b> memories ranked by semantic relevance</>}</div>}<small className="count"><b>{results.length}</b> {q?'memories that might help':'memories'}</small>{results.map((m,i)=><Card m={m} open={open} detailed={!!q} rank={q&&i<3?i+1:null} key={m.id}/>)}</section>}
function Card({m,open,detailed,rank}){return <article className="card" onClick={()=>open(m)}><div className="meta"><span>{m.type}</span><small>{m.office} · {m.year}</small></div><h3>{m.title}</h3><p>{m.summary}</p>{detailed&&<div className="why"><Sparkles size={13}/><span><b>{rank===1?'Strong match':rank===2?'Related memory':'Potentially useful'}:</b> {whyFor(m)}.</span></div>}<footer>{m.tags.map(t=><em key={t}>{t}</em>)}<b><ArrowUpRight size={15}/></b></footer></article>}
function whyFor(m){const t=m.tags.join(', ');return t+' connects to the ideas in your question'}
function People(){return <section className="page"><div className="title"><div><small>THE PEOPLE BEHIND THE WORK</small><h1>People</h1><p>Knowledge is easier to use when you know who made it.</p></div></div><div className="people">{people.map(p=><article key={p[0]}><div className="phead"><b>{p[4]}</b><small>{p[3]}</small></div><h3>{p[1]}</h3><p>{p[2]}</p><small>Contributed to {memories.filter(m=>m.people.includes(p[0])).length} memories.</small><footer><span>View memories</span><ChevronRight size={13}/></footer></article>)}</div></section>}
function Projects(){return <section className="page"><div className="title"><div><small>WORK THAT HOLDS THE KNOWLEDGE</small><h1>Projects</h1><p>Context is easier to understand when it's connected to the work.</p></div></div><div className="projects">{projects.map(p=><article key={p[0]}><small>{p[3]}</small><div><label>{p[2]}</label><h3>{p[1]}</h3><p>{p[4]}</p><footer>{memories.filter(m=>m.projectId===p[0]).length} memories <ChevronRight size={13}/></footer></div></article>)}</div></section>}
function Modal({m,close,open,flash}){const proj=projectById(m.projectId);return <div className="overlay" onMouseDown={e=>e.target===e.currentTarget&&close()}><div className="modal"><button className="close" onClick={close}><X/></button><div className="modalmeta"><span>{m.type}</span><small><MapPin/>{m.office}</small><small><Clock3/>{m.year}</small></div><h1>{m.title}</h1><p className="summary">{m.summary}</p><div className="whybig"><Sparkles/><div><b>WHY YOU'RE SEEING THIS</b><p>This memory is connected through its concepts, context and project relationships — not just exact words.</p></div></div>{[['Context',m.context],['What we tried',m.tried],['What we learned',m.finding],['Decision',m.decision],['Looking back',m.looking]].map(([a,b],i)=>b&&<div className={'info '+(i===2?'highlight':'')} key={a}><h4>{a}</h4><p>{b}</p></div>)}<div className="connections"><div><small>PEOPLE INVOLVED</small><h3>Talk to someone who knows</h3>{m.people.map(id=>{const p=personById(id);return <button key={id}><b>{p?.[4]}</b><span>{p?.[1]} · {p?.[2]}</span><ChevronRight/></button>})}</div><div><small>CONNECTED TO</small><h3>{proj?proj[1]:'New memory'}</h3>{m.related.map(id=>{const r=memories.find(x=>x.id===id);return r&&<button key={id} onClick={()=>open(r)}><Link2/><span>{r.title}</span><ChevronRight/></button>})}</div></div><div className="modalfoot"><button onClick={()=>flash('Forking is the next prototype interaction')}><Link2/> Fork this memory</button><span><Check/> Source context preserved</span></div></div></div>}
function Add({form,setForm,close,save}){return <div className="overlay"><div className="addmodal"><button className="close" onClick={close}><X/></button><small className="kicker">CONTRIBUTE TO THE COLLECTIVE</small><h1>What did you learn?</h1><p className="summary">Keep it lightweight. AI can help organise the memory after you save it.</p><label>Title<input value={form.title} onChange={e=>setForm({...form,title:e.target.value})} placeholder="e.g. Motion exposed a problem we couldn't see in static screens"/></label><label>Context<textarea value={form.context} onChange={e=>setForm({...form,context:e.target.value})} placeholder="What were you working on?"/></label><label>What should someone else know?<textarea value={form.finding} onChange={e=>setForm({...form,finding:e.target.value})} placeholder="What did you learn?"/></label><div className="twocol"><label>Type<select value={form.type} onChange={e=>setForm({...form,type:e.target.value})}><option>Learning</option><option>Decision</option><option>Experiment</option><option>Reflection</option></select></label><label>Office<select value={form.office} onChange={e=>setForm({...form,office:e.target.value})}>{['Amsterdam','Barcelona','Bonn','London','Oslo'].map(x=><option key={x}>{x}</option>)}</select></label></div><div className="modalfoot"><span>AI indexing runs in your browser.</span><button className="primary" onClick={save}><Plus size={14}/> Save memory</button></div></div></div>}
createRoot(document.getElementById('root')).render(<App/>);
